export enum Rotas {
    REMESSA = 1,
    ATOS_PESSOAL = 2,
    DOCUMENTOS = 3,
    RECURSO = 4,
    OBRAS = 5,
    INTIMACOES = 6,
    AREA_TRABALHO = 7,
    CONTRATO_LICITACAO = 8,
    LEGISLACAO = 9,
    PROCESSO = 10,
    CONSULTA_REMESSA_PROCESSO = 11,
    BENEFICIOS_PREVIDENCIARIO = 12
}
