export enum SubTipoRemessa {
    ENVIO_PREVIO = 1,
    HOMOLOGACAO = 2,
    INSTRUMENTO_CONTRATUAL = 3,
    ALTERACAO_CONTRATUAL = 4,
    EXECUCAO_CONTRATUAL = 5,
    MEDICAO = 6,
    RECEBIMENTO_PROVISORIO = 7,
    ENVIO_POSTERIOR_EDITAL = 8,
    RECEBIMENTO_DEFINITIVO = 9
}

