export enum TipoProcesso {
    BENEFICIO_PREVIDENCIARIOS = 155,

    ADESAO_ATA = 133,
    CONTRATO_ADIMINISTRATIVO = 8,
    CONTRATO_DE_TRANSPORTE_ESCOLAR = 91,
    INEXIBILIDADE_DISPENSA_E_CONTRATO_ADMINISTRATIVO = 141,
    LICITACAO_CONTRATO_DE_OBRAS = 160,
    LICITACAO_CONTRATO_ADMINSTRATIVO = 84,
    LICITACAO_CONTRATO_DE_TRANSPORTE_ESCOLAR = 89,
    UTILIZACAO_ATA_REGISTRO_DE_PRECO = 145,

    ATA_REGISTRO_PRECO = 140,
    INEXIBILIDADE_DISPENSA_ADMINISTRATIVO = 130,
    INEXIBILIDADE_DISPENSA_OBRAS = 131,
    LICITACAO_ADMINISTRATIVO = 125,
    LICITACAO_TRANSPORTE_ESCOLAR = 129,
    LICITACAO_OBRAS_SERVICOS_DE_ENGENHARIA = 127,
}
