export enum TipoEnvio {
    EDITAL = 1,
    TIPO_PARECER = 2,
    TIPO_PROJETO = 3,
    TIPO_PUBLICACAO = 5,
    TIPO_ORCAMENTO_BASE = 5,
    DESENHO = 4,
    TIPO_ALTERACAO_CONTRATUAL = 8,
    TIPO_RECURSO_ORCAMENTARIO = 10,
}
